### PR TITLE
Include configuration file

### PR DESCRIPTION
**Pull request by masonicGIT**
Includes a configuration file with a max block size setting.

### CODE REVIEW

**Comment by desantis** [comment]
Please add a description to your pull.

**Comment by desantis** [comment]
### Note:

screen shot 2017-07-16 at 8 14 24 pm

**Comment by desantis** [comment]
Much better!

RFC @cshrem

**Review by SilentTrader — CHANGES_REQUESTED** [review]
print "lets make monies jihan , more monies more boob coming"

**Comment by cshrem** [comment]
MERGED MOFO

**Pull request merged**
