### PR TITLE
add: my pub key

### PR DESCRIPTION
**Pull request by desantis**
I need to find the private key (it is in cold storage), but could you go ahead and merge the pub key?

### CODE REVIEW

**Comment by h0jeZvgoxFepBQ2C** [comment]
Since this is a private developed repo, you forgot to add your private key too. 

NACK.

**Comment by h0jeZvgoxFepBQ2C** [comment]
And be sure that we can verify your key via the Craig-Right-key-validation-system!

**Comment by SilentTrader** [comment]
meanwhile you can use my pubkey first

1HqDRzE8rQeAZkJzogrkssVN8h7bYLn1az

**Comment by h0jeZvgoxFepBQ2C** [comment]
@SilentTrader LGTM, can be merged.

**Comment by ghost** [comment]
I recommend taking your private key out of the freezer and adding it in a separate commit. But for now, ACK

**Comment by cshrem** [comment]
We buying desantis a boat

**Pull request merged**
